
version: "3.0"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
    - ../src:/var/www
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/sites/:/etc/nginx/sites-available
    ports:
    - "80:80"
